/* CIJ Materiais 1.79.4 — busca de peças e faturamento único no encerramento da OS. */
(function(){'use strict';
 const VERSION='1.79.4',BASE=['artifacts','plataforma-cij','public','data'];
 const PERMISSIONS={solicitar:'Solicitar peças na OS e preencher a solicitação técnica',entregar:'Entregar peças ao técnico',receber_devolucao:'Conferir e receber devoluções',transferir:'Transferir materiais entre técnicos / OS',vincular_orcamento:'Revisar vínculos de peças em registros anteriores',faturar:'Confirmar faturamento no encerramento da OS',liberar_saida:'Conferir e liberar entrega do equipamento',tratar_ocorrencias:'Resolver perdas e autorizar exceções justificadas',gerenciar_estoque:'Cadastrar, ajustar e administrar estoque',revisar_parque:'Revisar e converter temporários para o parque',configurar:'Configurar prazos de materiais'};
 const NAMES={PENDENTE:'Solicitado',RESERVADO:'Reservado',AGUARDANDO_RECEBIMENTO:'Entrega aguardando recebimento',EM_TESTE:'Peça em teste',COM_TECNICO:'Com o técnico',NA_MAQUINA:'Na máquina · aguarda faturamento',AGUARDANDO_DEVOLUCAO:'Devolução aguardando estoque',TRANSFERENCIA_PENDENTE:'Transferência aguardando aceite',UTILIZADO:'Aplicado no equipamento',DEVOLVIDO:'Guarda encerrada',CANCELADO:'Cancelado',OCORRENCIA_ABERTA:'Ocorrência pendente',REJEITADO:'Rejeitado'};
 const statusKey=r=>r.status==='APLICADO_PENDENTE_FATURAMENTO'?'UTILIZADO':r.status;
 const OFFLINE=new Set(['CREATE_REQUEST','RECEIVE','REQUEST_RETURN','TRANSFER','ACCEPT_TRANSFER','QUOTE_REQUEST','CONSUME','INCIDENT','CANCEL','SYNC_TECH_REQUEST']);
 const BUSINESS=new Set(['functions/failed-precondition','functions/aborted','functions/permission-denied','functions/invalid-argument','functions/not-found','functions/already-exists']);
 const ctx={os:null,equipment:null,refresh:null,central:false,tab:'entregar',data:{requests:[],catalog:[],staff:[],orders:[],alerts:[],history:[],quarantine:[]},uid:''};let dbPromise,callPromise,syncPromise,epoch=0;
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const qty=x=>Number(x||0).toLocaleString('pt-BR',{maximumFractionDigits:6});
 const uid=()=>window.currentUser?.uid||'';
 const mail=()=>String(window.currentUser?.email||'').toLowerCase();
 const profile=()=>window.userProfile||{};
 const master=()=>profile().perfil==='Master'||['marcos@grupocij.com','marcos@grupocij.com.br','adm@grupocij.com','adm@grupocij.com.br','marcos.bazacas@grupocij.com','marcos.bazacas@grupocij.com.br'].includes(mail());
 function can(key){if(master())return true;const p=profile();if(key==='faturar'&&(p.permissoesAssistencia?.faturar_encerrar===true||window.assistPermissions?.faturar_encerrar===true))return true;if(Object.hasOwn(p.permissoesMateriais||{},key))return p.permissoesMateriais[key]===true;return key==='solicitar'&&['Técnico','Tecnico'].includes(p.perfil);}
 const own=r=>master()||r.guardaEmail===mail()||(!r.guardaEmail&&r.autor_email===mail());
 const q=r=>r.quantidades||{};
 const custody=r=>(q(r).recebida||0)-(q(r).utilizada||0)-(q(r).devolvida||0)-(q(r).transferida||0)-(q(r).perdida||0);
 const transit=r=>(q(r).entregue||0)-(q(r).recebida||0)-(q(r).perdidaTransito||0);
 const free=r=>custody(r)-(q(r).devolucaoPendente||0)-(r.transferencia?.quantidade||0)-(r.ocorrencia?.origem==='CUSTODIA'?r.ocorrencia.quantidade:0);
 const isMine=r=>own(r)||r.transferencia?.recipientEmail===mail()||r.criadoPorUid===uid();
 const materialName=x=>String(x.nome||x.name||x.material||x.descricao||x.id||'');
 const materialCode=x=>String(x.codigo||x.sku||x.code||'');
 const searchText=x=>String(x??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR');
 const materialKey=x=>[x.origin,x.materialTipo,x.id].join('|');
 const originName=x=>x.origin==='RS'?'Filial RS':'Matriz';
 function materialPickerHTML(){return `<section class="mat-full mat-picker" id="mat-catalog-label"><label class="mat-label" for="mat-material-search">Buscar peça ou material pelo nome ou código</label><input id="mat-material-search" class="mat-input" type="search" autocomplete="off" placeholder="Digite parte do nome ou o código da peça" aria-controls="mat-material-results"><input name="materialChoice" type="hidden"><div class="mat-help" id="mat-material-count" role="status" aria-live="polite"></div><div id="mat-material-selected" class="mat-selected" hidden></div><div id="mat-material-results" class="mat-picker-results" role="listbox" aria-label="Peças encontradas"></div></section>`;}
 function bindMaterialPicker(form){
  const search=form.querySelector('#mat-material-search'),results=form.querySelector('#mat-material-results'),count=form.querySelector('#mat-material-count'),selected=form.querySelector('#mat-material-selected'),value=form.elements.materialChoice;
  function render(){
   const tokens=searchText(search.value).split(/\s+/).filter(Boolean),origin=form.elements.origin.value;
   const rows=ctx.data.catalog.filter(x=>x.origin===origin&&tokens.every(t=>searchText([materialCode(x),materialName(x),x.marca,x.modelo].filter(Boolean).join(' ')).includes(t))).sort((a,b)=>materialName(a).localeCompare(materialName(b),'pt-BR'));
   const visible=rows.slice(0,40);results.hidden=!!value.value;count.textContent=value.value?'Peça selecionada. Digite outra busca ou use Trocar peça para alterar.':rows.length?`${rows.length} material(is) encontrado(s).${rows.length>40?' Mostrando 40; digite mais para refinar a busca.':''}`:'Nenhum material encontrado nesta origem. Tente outro nome ou código.';
   results.innerHTML=visible.map(x=>`<button type="button" class="mat-material-option" role="option" aria-selected="${value.value===materialKey(x)}" data-material-key="${esc(materialKey(x))}"><span class="mat-material-name">${esc(materialName(x))}</span><span class="mat-meta">${esc(materialCode(x)||'Sem código')} · ${esc(originName(x))} · ${x.materialTipo==='CONSUMIVEL'?'Consumível':'Peça'} · Disponível: ${qty(Math.max(0,Number(x.estoqueAtual??x.quantity??x.qtd??x.quantidade??0)-Number(x.materiaisReservado||0)))} ${esc(x.unidade||x.unit||'UN')}</span></button>`).join('');
   results.querySelectorAll('[data-material-key]').forEach(button=>button.onclick=()=>{
    const x=rows.find(item=>materialKey(item)===button.dataset.materialKey);if(!x)return;
    value.value=materialKey(x);selected.hidden=false;selected.innerHTML=`<span class="mat-meta">Peça selecionada</span><strong class="mat-material-name">${esc(materialName(x))}</strong><span class="mat-meta">${esc(materialCode(x)||'Sem código')} · ${esc(originName(x))}</span><button class="mat-btn" type="button" id="mat-change-material">Trocar peça</button>`;
    selected.querySelector('button').onclick=()=>{reset();search.focus();};render();
   });
  }
  function reset(){value.value='';search.value='';selected.hidden=true;selected.innerHTML='';render();}
  search.addEventListener('input',()=>{value.value='';selected.hidden=true;selected.innerHTML='';render();});
  render();return {reset};
 }
 function database(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const open=indexedDB.open('cij-materiais-os-v3',1);open.onupgradeneeded=()=>{const d=open.result;d.createObjectStore('cache');const queue=d.createObjectStore('queue',{keyPath:'id'});queue.createIndex('uid','uid');};open.onsuccess=()=>resolve(open.result);open.onerror=()=>reject(open.error);});return dbPromise;}
 async function storage(store,mode,fn){const d=await database();return new Promise((resolve,reject)=>{const tx=d.transaction(store,mode),s=tx.objectStore(store);let result;const req=fn(s);if(req)req.onsuccess=()=>result=req.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
 const cache=(key,data,user=uid())=>storage('cache','readwrite',s=>s.put(data,user+'|'+key));
 const cached=(key,user=uid())=>storage('cache','readonly',s=>s.get(user+'|'+key));
 const jobs=()=>storage('queue','readonly',s=>s.index('uid').getAll(uid()));
 function actor(){if(!uid()||!mail())throw Error('Entre no portal para continuar.');if(ctx.uid&&ctx.uid!==uid()){ctx.data={requests:[],catalog:[],staff:[],orders:[],alerts:[],history:[],quarantine:[]};ctx.uid='';epoch++;document.getElementById('mat-overlay')?.remove();}return uid();}
 async function transport(data,actorId){if(uid()!==actorId)throw Error('A conta mudou. Abra novamente o módulo.');if(window.__CIJMateriaisCall)return window.__CIJMateriaisCall(data);if(!callPromise)callPromise=Promise.all([import('https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/11.6.1/firebase-functions.js')]).then(([a,f])=>f.httpsCallable(f.getFunctions(a.getApp(),'us-central1'),'cijMateriaisOS',{timeout:60000}));const call=await callPromise;if(uid()!==actorId)throw Error('A conta mudou.');return (await call(data)).data;}
 async function execute(action,payload){const actorId=actor(),job={id:crypto.randomUUID(),uid:actorId,email:mail(),action,payload:JSON.parse(JSON.stringify(payload)),createdAtISO:new Date().toISOString(),state:'PENDENTE'};if(!navigator.onLine&&!OFFLINE.has(action))throw Error('Esta conferência exige internet e confirmação do servidor.');await storage('queue','readwrite',s=>s.put(job));if(!navigator.onLine)return {queued:true,operationId:job.id};return dispatch(job);}
 async function dispatch(job){if(uid()!==job.uid)throw Error('Esta operação pertence a outra conta.');try{const result=await transport({operationId:job.id,action:job.action,payload:job.payload},job.uid);await storage('queue','readwrite',s=>s.delete(job.id));if(uid()===job.uid&&result.request){ctx.data.requests=ctx.data.requests.filter(x=>x.id!==result.request.id).concat(result.request);await cache('data',ctx.data,job.uid);}return result;}catch(e){job.state=BUSINESS.has(e.code)&&!(job.action==='CREATE_REQUEST'&&e.code==='functions/not-found')?'REVISAR':'PENDENTE';job.error=e.message||String(e);await storage('queue','readwrite',s=>s.put(job));throw e;}}
 async function sync(){if(syncPromise)return syncPromise;const actorId=actor();syncPromise=(async()=>{if(window.MaterialOS?.beforeSync)await window.MaterialOS.beforeSync();const all=await jobs(),blocked=new Set();let sent=0;for(const job of all){if(uid()!==actorId)break;if(job.state==='REVISAR'){if(job.payload.requestId)blocked.add(job.payload.requestId);continue;}if(blocked.has(job.payload.requestId))continue;try{await dispatch(job);sent++;}catch(e){if(job.payload.requestId)blocked.add(job.payload.requestId);if(!BUSINESS.has(e.code))break;}}return sent;})().finally(()=>syncPromise=null);return syncPromise;}
 async function read(collection,field,value,sub){const ref=sub?window.fsCollection(window.AppDB,...BASE,'os_ordens',sub.osId,collection):window.fsCollection(window.AppDB,...BASE,collection);const query=field?window.fsQuery(ref,window.fsWhere(field,'==',value)):ref;const snap=await window.fsGetDocs(query);const rows=[];snap.forEach(d=>rows.push({...d.data(),id:d.id}));return rows;}
 async function load(force=false){const actorId=actor(),stamp=++epoch;if(!navigator.onLine){const d=await cached('data',actorId);if(!d)throw Error('Prepare os materiais com internet antes do uso offline.');if(uid()===actorId&&stamp===epoch)ctx.data=d;return ctx.data;}
  const result=await Promise.allSettled([read('requisicoes_material'),read('cadastros_pecas'),read('cadastros_consumiveis'),read('estoque_rs'),read('usuarios_permissoes'),read('os_ordens'),read('materiais_alertas'),read('materiais_historico'),read('materiais_quarentena')]);
  if(result[0].status==='rejected')throw result[0].reason;const list=i=>result[i].status==='fulfilled'?result[i].value:[];
  const data={workflow:ctx.data.workflow||{},requests:list(0),catalog:[...list(1).filter(x=>x.ativo!==false&&!x.is_deleted).map(x=>({...x,origin:'MATRIZ',materialTipo:'PECA'})),...list(2).filter(x=>x.ativo!==false&&!x.is_deleted).map(x=>({...x,origin:'MATRIZ',materialTipo:'CONSUMIVEL'})),...list(3).map(x=>({...x,origin:'RS',materialTipo:'PECA'}))],staff:list(4).filter(x=>x.ativo!==false&&x.active!==false),orders:list(5).filter(x=>x.ativo!==false&&!x.is_deleted),alerts:list(6),history:list(7),quarantine:list(8)};
  if(!master()&&!['entregar','receber_devolucao','faturar','vincular_orcamento','liberar_saida','tratar_ocorrencias'].some(can)){data.requests=data.requests.filter(isMine);data.alerts=data.alerts.filter(x=>x.guardaEmail===mail()||x.destinatarioEmail===mail());const source=new Map(list(0).map(x=>[x.id,x])),allowed=new Set();data.lineages={};for(const row of data.requests){let current=row,chain=[],steps=0;while(current&&steps++<100){if(chain.includes(current.id))break;chain.push(current.id);allowed.add(current.id);current=source.get(current.parentRequestId);}data.lineages[row.id]=chain;}data.history=data.history.filter(x=>x.actorUid===actorId||allowed.has(x.requestId));}
  if(uid()!==actorId||stamp!==epoch)throw Error('A conta ou a tela mudou durante o carregamento.');ctx.uid=actorId;ctx.data=data;await cache('data',data,actorId);return data;
 }
 function options(rows,selected='',label=x=>x.nome||x.name||x.material||x.id){return rows.map(x=>`<option value="${esc(x.id)}" ${x.id===selected?'selected':''}>${esc(label(x))}</option>`).join('');}
 function field(name,label,type='text',value='',extra=''){return `<label class="mat-label">${esc(label)}<input class="mat-input" name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
 function select(name,label,items,selected=''){return `<label class="mat-label">${esc(label)}<select class="mat-input" name="${name}">${items.map(([v,t])=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;}
 const check=(name,label)=>`<label class="mat-check mat-full"><input type="checkbox" name="${name}" required><span>${esc(label)}</span></label>`;
 const reason=(label='Motivo / observações',required=true)=>`<label class="mat-label mat-full">${esc(label)}<textarea class="mat-input" name="reason" rows="3" ${required?'required':''}></textarea></label>`;
 function overlay(title,body){document.getElementById('mat-overlay')?.remove();const el=document.createElement('div');el.id='mat-overlay';el.className='mat-overlay mat-shell';el.innerHTML=`<section class="mat-dialog" role="dialog" aria-modal="true"><header class="mat-dialog-head"><div><h2>${esc(title)}</h2><div class="mat-meta">${esc(ctx.os?.osNumber||ctx.os?.numero||'')}${ctx.equipment?' · '+esc(ctx.equipment.modelo||'Equipamento'):''}</div></div><button class="mat-btn" data-close aria-label="Fechar">✕</button></header><div class="mat-dialog-body">${body}</div></section>`;document.body.appendChild(el);el.querySelector('[data-close]').onclick=()=>{el.remove();};return el;}
 async function form(title,html,submit){const el=overlay(title,`<form id="mat-form"><div class="mat-grid">${html}</div><div class="mat-alert" id="mat-form-error" style="display:none"></div><div class="mat-actions"><button class="mat-btn" type="button" id="mat-back">Voltar</button><button class="mat-btn primary" type="submit">Confirmar</button></div></form>`);el.querySelector('#mat-back').onclick=()=>showViewer();el.querySelector('form').onsubmit=async e=>{e.preventDefault();const error=el.querySelector('#mat-form-error'),button=e.submitter;error.style.display='none';button.disabled=true;const vals=Object.fromEntries(new FormData(e.target).entries());e.target.querySelectorAll('input[type="checkbox"]').forEach(x=>vals[x.name]=x.checked);try{const result=await submit(vals);if(result?.queued){error.textContent='Registro guardado neste aparelho. Aguardando sincronização e confirmação do servidor; não comprova retirada, aplicação ou liberação.';error.style.display='block';button.textContent='Registro guardado';await showViewer();}else{await load(true);await ctx.refresh?.();await showViewer();}}catch(err){error.className='mat-alert error';error.textContent=err.message||String(err);if(err.details?.duplicates?.length){error.innerHTML=esc(err.message)+'<div class="mat-actions">'+err.details.duplicates.map(x=>`<button type="button" class="mat-btn" data-link="${esc(x.id)}">Vincular ao existente: ${esc(x.modelo||x.id)}</button>`).join('')+'</div>';error.querySelectorAll('[data-link]').forEach(b=>b.onclick=async()=>{try{await submit({...vals,existingParkId:b.dataset.link});await load(true);await ctx.refresh?.();el.remove();}catch(e){error.textContent=e.message;}});}error.style.display='block';button.disabled=false;}};return el;}
 function requestList(){let rows=ctx.data.requests;if(ctx.os)rows=rows.filter(r=>r.osId===ctx.os.id||r.osId===ctx.os.internalId||r.os===(ctx.os.osNumber||ctx.os.numero));if(ctx.equipment)rows=rows.filter(r=>r.equipamentoId===ctx.equipment.id||r.equipamentoId===ctx.equipment.internalId);return rows.sort((a,b)=>String(b.createdAtISO||b.data_solicitacao||'').localeCompare(String(a.createdAtISO||a.data_solicitacao||'')));}
 function actions(r,advanced=false){
  const b=[],add=(a,t)=>b.push(`<button class="mat-btn ${['DELIVER','CONFIRM_RETURN'].includes(a)?'primary':''}" data-action="${a}" data-id="${esc(r.id)}">${t}</button>`);
  if(r.materialControlVersion!==3){if(can('entregar')&&!advanced&&!['CANCELADO','DEVOLVIDO','REJEITADO'].includes(r.status))add('RECONCILE_LEGACY','Conferir registro anterior');return b.join('');}
  const outside=custody(r)+transit(r),active=outside>0||(q(r).utilizada||0)>0;
  if(!advanced){
   if(can('entregar')&&!r.pedidoEncerrado&&!r.cancelado&&r.origemMaterial!=='CLIENTE')add('DELIVER','Entregar');
   if((can('receber_devolucao')||r.origemMaterial==='CLIENTE'&&own(r))&&outside>0&&!r.transferencia&&!r.ocorrencia)add('CONFIRM_RETURN','Receber devolução');
   if(can('solicitar')&&own(r)&&custody(r)>0)add('TECH_REQUEST','Solicitação técnica / peças');
   if(can('solicitar')&&(own(r)||can('entregar'))&&!r.pedidoEncerrado)add('CANCEL','Cancelar pedido restante');
   if(r.transferencia?.recipientEmail===mail()&&can('solicitar'))add('ACCEPT_TRANSFER','Receber do outro técnico');
  }else{
   if(can('solicitar')&&own(r)&&transit(r)>0)add('RECEIVE','Conferir entrega anterior');
   if(can('transferir')&&(own(r)||can('entregar'))&&free(r)>0&&!r.transferencia)add('TRANSFER','Trocar responsável / OS');
   if(r.transferencia&&(own(r)||can('entregar'))&&can('transferir'))add('CANCEL_TRANSFER','Cancelar transferência');
   if(r.stockPolicy!=='FATURAMENTO_OS'&&can('vincular_orcamento')&&r.origemMaterial!=='CLIENTE'&&active)add('BIND_BUDGET','Conferir vínculo anterior com orçamento');
   if(can('receber_devolucao')&&can('tratar_ocorrencias')&&(q(r).utilizada||0)>0)add('REVERSE_USE','Retirar peça aplicada antes do faturamento');
   if(can('faturar')&&can('tratar_ocorrencias')&&free(r)>0)add('EXEMPT','Autorizar garantia / cortesia');
   if(can('solicitar')&&own(r)&&!r.ocorrencia&&(free(r)>0||transit(r)>0))add('INCIDENT','Informar perda / dano');
   if(can('tratar_ocorrencias')&&r.ocorrencia)add('RESOLVE_INCIDENT','Resolver perda / dano');
  }
  return b.join('');
 }
 function location(r){const held=custody(r),planned=Math.min(held,Number(r.aplicacaoPlanejada?.quantidade||0));if(r.materialControlVersion!==3)return 'Conferência do registro anterior';if(held>0)return planned>0?`${qty(planned)} na máquina${held>planned?' · '+qty(held-planned)+' com '+(r.guardaNome||r.tecnico||'técnico'):''}`:`${qty(held)} com ${r.guardaNome||r.tecnico||'técnico'}`;if(transit(r)>0)return `${qty(transit(r))} na entrega anterior`;if((q(r).utilizada||0)>0)return `${qty(q(r).utilizada)} no equipamento · ${r.baixaFinalOS?'faturamento concluído':'aguarda faturamento'}`;if((q(r).perdida||0)+(q(r).perdidaTransito||0)>0)return 'Perda autorizada: '+qty((q(r).perdida||0)+(q(r).perdidaTransito||0))+((q(r).devolvida||0)>0?' · Devolvida: '+qty(q(r).devolvida):'');if((q(r).devolvida||0)>0)return 'Recebida de volta pelo administrativo';if((q(r).transferida||0)>0)return 'Transferida para outro responsável / atendimento';if(r.cancelado)return 'Pedido cancelado';return 'Aguardando entrega';}
 function card(r){return `<article class="mat-card mat-simple-card"><div class="mat-toolbar"><h3>${esc(r.material||'Material')}</h3><span class="mat-badge">${esc(NAMES[statusKey(r)]||r.status||'Conferir')}</span></div><div class="mat-meta">${esc(r.codigo||'')} · ${esc(r.equipamentoModelo||'')} · série ${esc(r.equipamentoNumeroSerie||'—')}</div><div class="mat-location">${esc(location(r))}</div><div class="mat-meta">Solicitada: ${qty(r.quantidadeSolicitada||r.qtd)} · Entregue: ${qty(q(r).entregue)}${(q(r).devolvida||0)>0?' · Devolvida: '+qty(q(r).devolvida):''}</div>${r.transferencia?`<div class="mat-alert">A guarda permanece com ${esc(r.guardaNome)} até ${esc(r.transferencia.recipientName)} confirmar o recebimento.</div>`:''}${r.ocorrencia?`<div class="mat-alert error">${esc(r.ocorrencia.motivo)}</div>`:''}<div class="mat-actions">${actions(r)}</div><details class="mat-details"><summary>Detalhes / ocorrências</summary><div class="mat-meta">${esc(r.os)} · ${esc(r.clienteNome||r.destino||'')}<br>Responsável: ${esc(r.guardaNome||r.tecnico||'—')} · ${esc(r.filial||r.origemMaterial||'Matriz')}${r.identificacaoSerie?' · Série da peça: '+esc(r.identificacaoSerie):''}${r.prazoRetorno?' · Conferir até '+esc(r.prazoRetorno):''}</div>${r.aplicacaoPlanejada?.quantidade?'<div class="mat-help">A inclusão na solicitação técnica indica a quantidade que ficará na máquina. O orçamento aprovado será conferido no faturamento.</div>':''}<div class="mat-actions">${actions(r,true)}<button class="mat-btn" data-history="${esc(r.id)}">Histórico</button></div></details></article>`;}
 async function bind(root){root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>operate(b.dataset.action,b.dataset.id).catch(e=>alert(e.message)));root.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>history(b.dataset.history));}
 async function queueHTML(){const all=await jobs();return all.length?`<div class="mat-alert"><b>${all.length} operação(ões) locais sem confirmação</b><div>Estoque e liberação dependem da confirmação no servidor.</div>${all.map(x=>`<div class="mat-card mat-meta">${esc(x.action)} · ${esc(x.state)}${x.error?' · '+esc(x.error):''}${x.state==='REVISAR'?`<button class="mat-btn" data-discard="${esc(x.id)}">Revisar / descartar tentativa recusada</button>`:''}</div>`).join('')}<button class="mat-btn primary" id="mat-sync">Sincronizar agora</button></div>`:'';}
 async function bindQueue(root){root.querySelector('#mat-sync')?.addEventListener('click',async()=>{try{await sync();await load(true);await showViewer();}catch(e){alert(e.message);}});root.querySelectorAll('[data-discard]').forEach(b=>b.onclick=async()=>{const job=(await jobs()).find(x=>x.id===b.dataset.discard);if(job?.state==='REVISAR'&&confirm('O servidor recusou esta tentativa. A cópia será removida; revise os dados atuais antes de criar outra operação.')){await storage('queue','readwrite',s=>s.delete(job.id));await showViewer();}});}
 async function showViewer(){if(ctx.central){document.getElementById('mat-overlay')?.remove();return renderCentral();}const el=overlay('Materiais / requisições da OS',`<div class="mat-toolbar"><div class="mat-help">Requisite aqui. Se a peça ficar na máquina, preencha Solicitação técnica / peças. O administrativo entrega e recebe as devoluções.</div><div class="mat-actions">${can('solicitar')?'<button class="mat-btn primary" id="mat-new">Requisitar peça</button>':''}${can('transferir')?'<button class="mat-btn" id="mat-held">Peça já comigo / transferir</button>':''}<button class="mat-btn" id="mat-refresh">Atualizar</button></div></div>${await queueHTML()}${can('transferir')&&ctx.data.requests.some(r=>own(r)&&r.osId!==(ctx.os?.id||ctx.os?.internalId)&&free(r)>0)?'<div class="mat-alert">Peça já sob sua guarda em outra OS? Use a aba Materiais comigo na central e transfira o registro para esta OS. O estoque não fará uma nova retirada.</div>':''}<div>${requestList().map(card).join('')||'<div class="mat-empty">Nenhum material requisitado para este equipamento.</div>'}</div>`);el.querySelector('#mat-new')?.addEventListener('click',()=>newRequest().catch(e=>alert(e.message)));el.querySelector('#mat-held')?.addEventListener('click',()=>held());el.querySelector('#mat-refresh').onclick=async()=>{try{await sync();await load(true);await showViewer();}catch(e){alert(e.message);}};await bind(el);await bindQueue(el);}
 async function held(){const rows=ctx.data.requests.filter(r=>r.materialControlVersion===3&&own(r)&&free(r)>0&&(!ctx.os||r.osId!==(ctx.os.id||ctx.os.internalId)||!ctx.equipment||r.equipamentoId!==(ctx.equipment.id||ctx.equipment.internalId)));const el=overlay('Peças já sob minha guarda',`<div class="mat-help">Selecione uma retirada registrada. A transferência será aceita no destino e não fará outra baixa no estoque.</div>${rows.map(r=>`<div class="mat-card"><b>${esc(r.material)}</b><div class="mat-meta">${esc(r.os)} · ${esc(r.equipamentoModelo)} · ${qty(free(r))} disponível(is) sob guarda</div><button class="mat-btn" data-held="${esc(r.id)}">Transferir para este atendimento</button></div>`).join('')||'<div class="mat-empty">Não há material disponível em outra retirada registrada. Se a peça já estava em um kit sem registro, solicite a conferência do estoque antes de aplicar.</div>'}<button class="mat-btn" id="mat-held-back">Voltar</button>`);el.querySelectorAll('[data-held]').forEach(b=>b.onclick=()=>operate('TRANSFER',b.dataset.held).catch(e=>alert(e.message)));el.querySelector('#mat-held-back').onclick=()=>showViewer();}
 async function newRequest(){
  if(!ctx.os&&!navigator.onLine)throw Error('Para requisitar sem internet, abra a OS preparada no app do técnico. Na central, selecione a OS com internet.');
  let eqs=ctx.os?ctx.os._equipamentos||[]:[];
  const html=`${ctx.os?'':select('osId','Ordem de serviço',ctx.data.orders.map(x=>[x.id,(x.osNumber||x.numero||x.id)+' · '+(x.clienteNome||x.cliente||'')]))}${ctx.equipment?'':select('equipmentId','Equipamento',eqs.map(x=>[x.id,x.modelo+' · '+(x.numeroSerie||'')]))}${can('entregar')?select('ownerEmail','Responsável que receberá a peça',ctx.data.staff.map(x=>[x.email||x.id,x.nome||x.email||x.id]),mail()):''}${select('origin','Origem',[['MATRIZ','Estoque CIJ — matriz'],['RS','Estoque CIJ — filial RS'],['CLIENTE','Peça fornecida pelo cliente']])}${materialPickerHTML()}<div class="mat-full mat-grid" id="mat-client-fields" hidden>${field('description','Descrição da peça do cliente')}${field('clientReceipt','Quem forneceu a peça do cliente')}</div>${select('purpose','Finalidade',[['TESTE','Para teste'],['APLICACAO','Aplicação — dependerá do orçamento aprovado']])}${field('quantity','Quantidade','number',1,'min="0.000001" step="0.000001" required')}${field('serial','Número de série da unidade (quando houver)')}${field('lot','Lote (quando houver)')}${field('deadline','Prazo previsto para teste / devolução','date','')}${reason('Motivo da requisição')}`;
  const el=await form('Requisitar material',html,async v=>{
   const parts=(v.materialChoice||'').split('|');
   if(v.origin!=='CLIENTE'&&!v.materialChoice)throw Error('Busque pelo nome ou código e toque na peça que deseja requisitar.');
   if(v.origin!=='CLIENTE'&&parts[0]!==v.origin)throw Error('Selecione uma peça do estoque de origem escolhido.');
   return execute('CREATE_REQUEST',{osId:ctx.os?.id||ctx.os?.internalId||v.osId,equipmentId:ctx.equipment?.id||ctx.equipment?.internalId||v.equipmentId,origin:v.origin,materialTipo:parts[1],materialId:parts[2],description:v.description,clientReceipt:v.clientReceipt,purpose:v.purpose,quantity:v.quantity,serial:v.serial,lot:v.lot,deadline:v.deadline,reason:v.reason,ownerEmail:v.ownerEmail||''});
  });
  const f=el.querySelector('form'),picker=bindMaterialPicker(f);
  f.elements.origin.onchange=()=>{
   const client=f.elements.origin.value==='CLIENTE';
   f.querySelector('#mat-catalog-label').hidden=client;f.querySelector('#mat-client-fields').hidden=!client;
   f.elements.description.required=client;f.elements.clientReceipt.required=client;picker.reset();
  };f.elements.origin.onchange();
  if(!ctx.equipment&&ctx.os&&!eqs.length){eqs=await read('equipamentos',null,null,{osId:ctx.os.id||ctx.os.internalId});f.elements.equipmentId.innerHTML=options(eqs,'',x=>x.modelo+' · '+(x.numeroSerie||''));}
  if(!ctx.os){f.elements.osId.onchange=async()=>{const oid=f.elements.osId.value;const list=await read('equipamentos',null,null,{osId:oid});f.elements.equipmentId.innerHTML=options(list,'',x=>x.modelo+' · '+(x.numeroSerie||''));};await f.elements.osId.onchange();}
 }
 async function operate(action,rid){const r=ctx.data.requests.find(x=>x.id===rid);if(!r)throw Error('Atualize a tela para ler esta requisição.');if(action==='TECH_REQUEST'){if(window.abrirSolicitacaoOrcamento&&ctx.os){document.getElementById('mat-overlay')?.remove();await window.abrirSolicitacaoOrcamento(r.equipamentoId);}else locationAssign(r);return;}const base={requestId:rid,expectedRevision:r.revision},num=(label,max)=>field('quantity',label,'number',max,'min="0.000001" step="0.000001" max="'+esc(max)+'" required');let html='';
  if(['RESERVE','DELIVER','RECEIVE','REQUEST_RETURN','CONSUME'].includes(action)){const max=action==='RESERVE'?r.quantidadeSolicitada-(q(r).entregue||0)-(q(r).reservada||0):action==='DELIVER'?r.quantidadeSolicitada-(q(r).entregue||0):action==='RECEIVE'?transit(r):free(r);html=num('Quantidade',max);if(['DELIVER','RECEIVE','CONSUME'].includes(action))html+=check('confirmPhysical',action==='DELIVER'?'Conferi a peça e entreguei fisicamente ao responsável.':action==='RECEIVE'?'Recebi fisicamente a peça indicada.':'A peça foi aplicada definitivamente neste equipamento.');if(action==='DELIVER')html+='<label class="mat-check mat-full"><input type="checkbox" name="complete"><span>Não entregar mais peças deste pedido (encerrar o restante).</span></label>';}
  if(action==='REVERSE_USE')html=num('Quantidade removida',q(r).utilizada)+reason('Motivo da remoção e conferência comercial')+check('confirmPhysical','Conferi que esta quantidade foi retirada fisicamente do equipamento.');
  if(action==='CONFIRM_RETURN')html=num('Quantidade recebida',custody(r)+transit(r))+select('condition','Destino / condição',r.origemMaterial==='CLIENTE'?[['CLIENTE','Devolvido ao cliente']]:[['DISPONIVEL','Íntegra — retornar ao disponível'],['QUARENTENA','Danificada / divergente — quarentena']])+field('serial','Série conferida (quando houver)','text','',r.identificacaoSerie?'required':'')+field('recipient','Recebedor, para peça do cliente')+reason('Observações da conferência',false)+check('confirmPhysical','Conferi fisicamente a quantidade, a identidade e a condição recebidas.');
  if(action==='TRANSFER')html=num('Quantidade a transferir',free(r))+select('recipientEmail','Novo responsável',ctx.data.staff.map(x=>[x.email||x.id,(x.nome||x.email||x.id)]),ctx.os&&(ctx.os.id||ctx.os.internalId)!==r.osId?mail():'')+select('targetOsId','OS de destino (pode manter a mesma)',ctx.data.orders.map(x=>[x.id,(x.osNumber||x.numero||x.id)+' · '+(x.clienteNome||x.cliente||'')]),ctx.os?.id||ctx.os?.internalId||r.osId)+select('targetEquipmentId','Equipamento de destino',[[r.equipamentoId,r.equipamentoModelo]])+reason('Motivo e local da entrega')+check('confirmPhysical','Conferi fisicamente o material e a entrega proposta ao novo responsável. O aceite dele continuará obrigatório.');
  if(action==='ACCEPT_TRANSFER')html=`<div class="mat-alert mat-full">${qty(r.transferencia?.quantidade)} · ${esc(r.material)} · entregue por ${esc(r.guardaNome)}</div>`+check('confirmPhysical','Recebi e conferi fisicamente a peça / quantidade.');
  if(action==='CANCEL_TRANSFER'||action==='CANCEL')html=reason('Motivo')+(action==='CANCEL_TRANSFER'&&r.guardaEmail!==mail()?check('confirmPhysical','Conferi fisicamente o material e o destino antes de cancelar esta transferência.'):'');
  if(action==='QUOTE_REQUEST')html=num('Quantidade a orçar',custody(r))+field('service','Serviço recomendado','text','','required')+field('hours','Tempo estimado (horas)','number',1,'min="0.01" step="0.01" required')+field('notes','Resultado do teste / observações');
  if(action==='BIND_BUDGET'){if(!navigator.onLine)throw Error('O vínculo com o orçamento exige internet.');const budgets=(await read('orcamentos',null,null,{osId:r.osId})).filter(x=>x.statusOrcamento==='APROVADO'&&x.equipamentoId===r.equipamentoId&&Number(x.cicloAtendimento||1)===Number(r.cicloAtendimento||1));if(!budgets.length)throw Error('Não há orçamento aprovado para este equipamento/ciclo.');html=select('budgetId','Orçamento aprovado',budgets.map(x=>[x.id,'V'+(x.versao||1)+' · '+x.id]))+select('itemIndex','Item aprovado',[])+check('confirmMatch','Conferi que o item aprovado corresponde exatamente à peça requisitada.');const el=await form('Vincular orçamento aprovado',`<div class="mat-alert mat-full"><b>${esc(r.material)}</b><br>${esc(r.os)} · ${esc(r.equipamentoModelo)}<br>Técnico responsável: ${esc(r.guardaNome||r.tecnico)}</div>`+html,v=>execute(action,{...base,...v}));const f=el.querySelector('form');f.elements.budgetId.onchange=()=>{const b=budgets.find(x=>x.id===f.elements.budgetId.value);f.elements.itemIndex.innerHTML=(b.itens||[]).map((x,i)=>`<option value="${i}">${esc(x.descricao)} · ${qty(x.quantidade)} aprovado(s)</option>`).join('');};f.elements.budgetId.onchange();return;}
  if(action==='EXEMPT')html=num('Quantidade',free(r))+select('kind','Natureza da autorização',[['GARANTIA','Garantia'],['CORTESIA','Cortesia'],['SERVICO_INTERNO','Serviço interno']])+reason('Justificativa comercial e autorização');
  if(action==='INCIDENT')html=select('source','Onde está a pendência',[...(free(r)>0?[['CUSTODIA','Em poder do técnico']]:[]),...(transit(r)>0?[['TRANSITO','Entrega ainda sem recebimento']]:[])])+num('Quantidade',Math.max(free(r),transit(r)))+reason('Descreva perda, dano ou divergência');
  if(action==='RESOLVE_INCIDENT')html=`<div class="mat-alert mat-full">${esc(r.ocorrencia?.motivo)} · ${qty(r.ocorrencia?.quantidade)}</div>`+select('disposition','Tratamento',[['REGULARIZADO','Conferido e regularizado — peça continua sob guarda'],['RETORNO_DANIFICADO','Recebido danificado — quarentena'],['PERDA','Perda confirmada e autorizada']])+reason('Conferência física, justificativa e autorização')+check('confirmPhysical','Conferi esta ocorrência e assumo o tratamento informado.');
  if(action==='RECONCILE_LEGACY')html=(!r.osId?select('osId','OS deste registro anterior',ctx.data.orders.map(x=>[x.id,(x.osNumber||x.numero||x.id)+' · '+(x.clienteNome||x.cliente||'')])):'')+(!r.equipamentoId?select('equipmentId','Equipamento desta OS',[]):'')+`<div class="mat-alert mat-full">A conferência não refaz automaticamente uma baixa anterior. Identifique a movimentação ou a conferência física utilizada como base.</div>`+select('materialId','Peça cadastrada',ctx.data.catalog.filter(x=>x.materialTipo==='PECA').map(x=>[x.id,(x.codigo||x.sku||x.code||'')+' · '+(x.nome||x.name||x.material||'')]),r.materialId||'')+select('origin','Origem',[['MATRIZ','Matriz'],['RS','Filial RS']])+select('ownerEmail','Responsável pela guarda',ctx.data.staff.map(x=>[x.email||x.id,x.nome||x.email||x.id]),r.guardaEmail||r.autor_email)+field('quantity','Quantidade física conferida','number',r.qtd||0,'min="0" step="0.000001" required')+select('basis','Situação física',[['JA_BAIXADO','Sob guarda — retirada anterior já baixada'],['RETIRAR_AGORA','Sob guarda — registrar primeira baixa agora'],['DEVOLVIDO','Devolução já conferida no saldo físico'],['APLICADO','Aplicado no equipamento — conferir orçamento']])+field('proof','Referência da movimentação / inventário / conferência','text','','required')+check('confirmPhysical','Conferi fisicamente o material, o responsável e a base do saldo anterior.');
  const el=await form(NAMES[action]||({RESERVE:'Reservar material',DELIVER:'Entrega pelo estoque',RECEIVE:'Recebimento pelo técnico',REQUEST_RETURN:'Solicitar devolução',CONFIRM_RETURN:'Receber devolução',TRANSFER:'Transferir material',ACCEPT_TRANSFER:'Aceitar transferência',QUOTE_REQUEST:'Resultado do teste para orçamento',CONSUME:'Confirmar aplicação autorizada',EXEMPT:'Autorização comercial especial',INCIDENT:'Registrar ocorrência',RESOLVE_INCIDENT:'Resolver ocorrência',RECONCILE_LEGACY:'Conferência de registro anterior',CANCEL:'Cancelar saldo do pedido'})[action]||action,`<div class="mat-alert mat-full"><b>${esc(r.material)}</b><br>${esc(r.os)} · ${esc(r.equipamentoModelo)}<br>Técnico responsável: ${esc(r.guardaNome||r.tecnico)}</div>`+html,v=>execute(action,{...base,...v}));
  if(action==='RECONCILE_LEGACY'&&!r.equipamentoId){const f=el.querySelector('form'),update=async()=>{const osId=r.osId||f.elements.osId?.value;if(!osId)return;const equipment=(await read('equipamentos',null,null,{osId})).filter(x=>x.ativo!==false&&!x.is_deleted);f.elements.equipmentId.innerHTML=options(equipment,'',x=>x.modelo+' · '+(x.numeroSerie||''));};if(f.elements.osId)f.elements.osId.onchange=update;await update();}
  if(action==='TRANSFER'){const f=el.querySelector('form');f.elements.targetOsId.onchange=async()=>{const target=f.elements.targetOsId.value;const eqs=navigator.onLine?(await read('equipamentos',null,null,{osId:target})).filter(x=>x.ativo!==false&&!x.is_deleted):ctx.os?._equipamentos||[{id:r.equipamentoId,modelo:r.equipamentoModelo}];f.elements.targetEquipmentId.innerHTML=options(eqs,ctx.equipment?.id||ctx.equipment?.internalId||'',x=>x.modelo+' · '+(x.numeroSerie||''));};await f.elements.targetOsId.onchange();}
 }
 async function history(rid){const r=ctx.data.requests.find(x=>x.id===rid),rows=ctx.data.history.filter(x=>(ctx.data.lineages?.[rid]||[rid,r?.parentRequestId,r?.rootRequestId]).includes(x.requestId)||x.rootRequestId===(r?.rootRequestId||rid)).sort((a,b)=>String(a.createdAtISO).localeCompare(String(b.createdAtISO)));const el=overlay('Histórico do material',`<div class="mat-help">${esc(r?.material)} · ${esc(rid)}</div>${r?.migracao?'<div class="mat-alert">Registro anterior preservado e conferido por '+esc(r.migracao.porUid)+' em '+esc(r.migracao.emISO)+'</div>':''}${rows.map(x=>`<div class="mat-card"><b>${esc(x.action)}</b><div class="mat-meta">${esc(x.actorNome||x.actorEmail)} · ${esc(x.createdAtISO)}<br>${esc(x.motivo||'')}${x.after?'<br>Guarda: '+esc(x.after.guardaEmail):''}</div></div>`).join('')||'<div class="mat-empty">Sem movimentos novos neste registro.</div>'}<button class="mat-btn" id="mat-history-back">Voltar</button>`);el.querySelector('#mat-history-back').onclick=()=>showViewer();}
 async function convert(os,equipment,refresh){ctx.os=os;ctx.equipment=equipment;ctx.refresh=refresh;ctx.central=false;if(!can('revisar_parque'))throw Error('Sem permissão para revisar equipamentos temporários.');const data={modelo:equipment.modelo||'',marca:equipment.marca||'',numeroSerie:equipment.numeroSerie||'',identificacaoLocal:equipment.identificacaoLocal||'',observacao:equipment.observacao||''};await form('Revisar equipamento temporário e cadastrar no parque',`<div class="mat-alert mat-full">Cliente: ${esc(os.clienteNome||os.cliente||'')}<br>Diagnósticos, fotos, formulários, peças e o identificador do equipamento nesta OS serão preservados.</div>${field('modelo','Modelo','text',data.modelo,'required')}${field('marca','Marca / fabricante','text',data.marca,'required')}${field('numeroSerie','Número de série','text',data.numeroSerie,'required')}${field('identificacaoLocal','TAG / identificação local','text',data.identificacaoLocal)}${field('observacao','Observações do equipamento','text',data.observacao)}${check('confirmReview','Revisei os dados e confirmei o cliente proprietário deste equipamento.')}`,v=>execute('CONVERT_EQUIPMENT',{osId:os.id||os.internalId,equipmentId:equipment.id||equipment.internalId,data:{modelo:v.modelo,marca:v.marca,numeroSerie:v.numeroSerie,identificacaoLocal:v.identificacaoLocal,observacao:v.observacao},confirmReview:v.confirmReview,existingParkId:v.existingParkId||''}));}
 async function release(os,equipment,refresh){ctx.os=os;ctx.equipment=equipment;ctx.refresh=refresh;ctx.central=false;await form('Conferir e liberar entrega do equipamento',field('recipient','Nome do recebedor / transportadora','text','','required')+reason('Observações',false)+check('confirmPhysical','Conferi fisicamente a máquina e as peças. A liberação depende também da validação no servidor.'),v=>execute('RELEASE_EQUIPMENT',{osId:os.id||os.internalId,equipmentId:equipment.id||equipment.internalId,...v}));}
 async function quarantine(id){const item=ctx.data.quarantine.find(x=>x.id===id);if(!item)throw Error('Atualize a quarentena.');await form('Avaliar unidade em quarentena',`<div class="mat-alert mat-full">${esc(item.material)} · ${qty(item.quantity)}</div>`+select('disposition','Destino após avaliação',[['REINTEGRAR','Reparada / íntegra — reintegrar ao disponível'],['DESCARTAR','Descartar com autorização']])+reason('Resultado da avaliação e justificativa')+check('confirmPhysical','Conferi fisicamente as unidades e o destino informado.'),v=>execute('RESOLVE_QUARANTINE',{quarantineId:id,...v}));}
 async function central(){actor();ctx.central=true;ctx.os=null;ctx.equipment=null;ctx.refresh=null;document.getElementById('main-content')?.classList.remove('hidden');try{await load();await sync();await renderCentral();}catch(e){const box=document.getElementById('mat-central');if(box)box.innerHTML='<div class="mat-alert error">'+esc(e.message)+'</div>';}}
 async function renderCentral(){
  const root=document.getElementById('mat-central');if(!root)return;
  const admin=['entregar','receber_devolucao','vincular_orcamento','faturar','tratar_ocorrencias'].some(can),tabs=admin?[['entregar','A entregar'],['entregues','Entregues / devoluções'],['historico','Histórico']]:[['minhas','Minhas peças'],['historico','Histórico']];
  if(!tabs.some(([k])=>k===ctx.tab))ctx.tab=tabs[0][0];
  const pending=ctx.data.requests.filter(r=>r.materialControlVersion===3&&!r.pedidoEncerrado&&!r.cancelado).length,held=ctx.data.requests.filter(r=>custody(r)>0||transit(r)>0).length;
  root.innerHTML=`<div class="mat-toolbar"><div><h1 style="font-size:22px;font-weight:800;margin:0">Peças das ordens de serviço</h1><div class="mat-help">${pending} pedido(s) a entregar · ${held} entrega(s) com peças fora do estoque</div></div><div class="mat-actions">${can('solicitar')?'<button class="mat-btn primary" id="mat-new">Solicitar peça</button>':''}<button class="mat-btn" id="mat-prepare">Atualizar</button><details class="mat-settings"><summary>Mais opções</summary><div class="mat-actions"><button class="mat-btn" id="mat-export">Exportar histórico</button>${admin?'<button class="mat-btn" data-tab="quarentena">Peças danificadas</button>':''}${can('configurar')?'<button class="mat-btn" id="mat-config">Prazo de conferência</button>':''}</div></details></div></div><nav class="mat-tabs">${tabs.map(([k,n])=>`<button class="mat-btn ${k===ctx.tab?'active':''}" data-tab="${k}">${n}</button>`).join('')}</nav>${await queueHTML()}<div class="mat-filter"><input class="mat-input" id="mat-search" placeholder="Buscar por OS, cliente, peça ou técnico"><select class="mat-input" id="mat-status"><option value="">Todas as situações</option>${Object.entries(NAMES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select><input class="mat-input" id="mat-date" type="date" aria-label="Data inicial"></div><div id="mat-central-list"></div>`;
  root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{ctx.tab=b.dataset.tab;if(ctx.tab==='quarentena'){renderCentralList();}else renderCentral();});root.querySelector('#mat-new')?.addEventListener('click',()=>newRequest().catch(e=>alert(e.message)));root.querySelector('#mat-prepare').onclick=async()=>{try{await sync();await load(true);await renderCentral();}catch(e){alert(e.message);}};root.querySelector('#mat-export').onclick=()=>exportCSV();root.querySelector('#mat-config')?.addEventListener('click',()=>form('Prazo de conferência',field('testDays','Dias para conferir peças fora do estoque','number',5,'min="1" max="30" required'),v=>execute('CONFIG',v)));root.querySelectorAll('#mat-search,#mat-status,#mat-date').forEach(x=>x.oninput=()=>renderCentralList());await bindQueue(root);renderCentralList();
 }
 function renderCentralList(){
  const root=document.getElementById('mat-central'),box=root?.querySelector('#mat-central-list');if(!box)return;
  if(ctx.tab==='quarentena'){box.innerHTML='<h2>Peças danificadas / em avaliação</h2>'+ctx.data.quarantine.map(x=>`<div class="mat-card"><b>${esc(x.material)}</b><div class="mat-meta">${qty(x.quantity)} · ${esc(x.motivo)} · ${esc(x.status)}</div>${x.status==='EM_AVALIACAO'&&can('receber_devolucao')&&can('tratar_ocorrencias')?`<button class="mat-btn" data-quarantine="${esc(x.id)}">Avaliar peça recebida</button>`:''}</div>`).join('');box.querySelectorAll('[data-quarantine]').forEach(b=>b.onclick=()=>quarantine(b.dataset.quarantine).catch(e=>alert(e.message)));return;}
  let rows=ctx.data.requests;
  if(ctx.tab==='entregar')rows=rows.filter(r=>r.materialControlVersion===3?!r.pedidoEncerrado&&!r.cancelado:!['CANCELADO','DEVOLVIDO','REJEITADO'].includes(r.status));
  if(ctx.tab==='entregues')rows=rows.filter(r=>custody(r)>0||transit(r)>0||r.ocorrencia||r.transferencia||(q(r).utilizada||0)>0&&!r.baixaFinalOS&&!ctx.data.orders.find(o=>o.id===r.osId)?.encerradoAdministrativamente);
  if(ctx.tab==='minhas')rows=rows.filter(r=>isMine(r)&&(!r.pedidoEncerrado&&!r.cancelado||custody(r)>0||transit(r)>0||r.ocorrencia||r.transferencia));
  const search=searchText(root.querySelector('#mat-search').value),stat=root.querySelector('#mat-status').value,date=root.querySelector('#mat-date').value;
  rows=rows.filter(r=>(!stat||statusKey(r)===stat)&&(!date||(r.createdAtISO||r.data_solicitacao||'').slice(0,10)>=date)&&(!search||search.split(/\s+/).every(t=>searchText([r.material,r.codigo,r.os,r.clienteNome,r.destino,r.equipamentoModelo,r.equipamentoNumeroSerie,r.guardaNome,r.tecnico,r.identificacaoSerie].join(' ')).includes(t))));
  const groups=new Map();for(const row of rows){const key=row.osId||row.os||'sem-os';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row);}
  box.innerHTML=rows.length?`<div class="mat-help">${rows.length} peça(s) / pedido(s) em ${groups.size} OS</div>`+[...groups.values()].map(list=>{const r=list[0];return `<section class="mat-os-group"><header class="mat-os-head"><div><strong>${esc(r.os||'OS a conferir')}</strong><div class="mat-meta">${esc(r.clienteNome||r.destino||'')}</div></div><a class="mat-btn" href="assistencia.html?os=${encodeURIComponent(r.osId||r.os||'')}">Abrir OS</a></header><div class="mat-os-parts">${list.map(card).join('')}</div></section>`;}).join(''):`<div class="mat-empty">${ctx.tab==='entregar'?'Nenhum pedido aguardando entrega.':ctx.tab==='entregues'?'Nenhuma peça pendente de devolução ou faturamento.':'Nenhum registro nesta pesquisa.'}</div>`;
  bind(box);
 }
 function locationAssign(r){window.location.href='assistencia.html?os='+encodeURIComponent(r.osId)+'&solicitacao='+encodeURIComponent(r.equipamentoId);}
 async function workflow(os){const oid=os.id||os.internalId;if(navigator.onLine){const [budgets,technical,equipment]=await Promise.all([read('orcamentos',null,null,{osId:oid}),read('solicitacoes_orcamento',null,null,{osId:oid}),read('equipamentos',null,null,{osId:oid})]);ctx.data.workflow=ctx.data.workflow||{};ctx.data.workflow[oid]={budgets,technical,equipment};await cache('data',ctx.data);}return ctx.data.workflow?.[oid];}
 async function technicalParts(os,equipment){await load();const oid=os.id||os.internalId,eid=equipment.id||equipment.internalId;return ctx.data.requests.filter(r=>r.materialControlVersion===3&&r.osId===oid&&r.equipamentoId===eid&&Number(r.cicloAtendimento||1)===Number(os.cicloAtendimento||1)&&custody(r)+(q(r).utilizada||0)>0).map(r=>({descricao:r.material,unidade:r.unidade,quantidade:Math.max(0,custody(r)+(q(r).utilizada||0)),materialRequestId:r.id,materialId:r.materialId,materialTipo:r.materialTipo,origemMaterial:r.origemMaterial,maxQuantidade:Math.max(0,custody(r)+(q(r).utilizada||0))}));}
 async function syncTechnical(os,equipment,data){const oid=os.id||os.internalId,eid=equipment.id||equipment.internalId;ctx.data.workflow=ctx.data.workflow||{};const w=ctx.data.workflow[oid]||{budgets:[],technical:[],equipment:os._equipamentos||[]};w.technical=w.technical.filter(x=>(x.internalId||x.id)!==(data.internalId||data.id)).concat(data);ctx.data.workflow[oid]=w;await cache('data',ctx.data);return execute('SYNC_TECH_REQUEST',{osId:oid,equipmentId:eid,technicalId:data.internalId||data.id});}
 async function validateFinish(os,equipment){
  const oid=os.id||os.internalId,eid=equipment?.id||equipment?.internalId;
  if(navigator.onLine){await sync();return execute('CHECK_FINISH',{osId:oid,...(eid?{equipmentId:eid}:{})});}
  await load();const rows=ctx.data.requests.filter(r=>r.osId===oid&&(!eid||r.equipamentoId===eid)),w=ctx.data.workflow?.[oid];
  for(const r of rows){if(r.materialControlVersion!==3&&!['DEVOLVIDO','CANCELADO','REJEITADO'].includes(r.status))throw Error('O estoque precisa conferir o registro anterior de '+r.material+'.');if(r.materialControlVersion!==3)continue;if(!r.pedidoEncerrado&&!r.cancelado||r.transferencia||r.ocorrencia||transit(r)>0||(q(r).devolucaoPendente||0)>0)throw Error('Há entrega ou devolução pendente de '+r.material+'.');const held=custody(r);if(held>0){const machine=(w?.equipment||os._equipamentos||[]).find(e=>(e.id||e.internalId)===r.equipamentoId),budget=w?.budgets.find(b=>(b.id||b.internalId)===machine?.ultimoOrcamentoId&&b.statusOrcamento==='APROVADO'),technical=w?.technical.find(t=>(t.id||t.internalId)===(budget?.solicitacaoOrcamentoId||machine?.solicitacaoOrcamentoId));const planned=(technical?.pecas||[]).filter(x=>x.materialRequestId===r.id).reduce((a,x)=>a+Number(x.quantidade||0),0),approved=(budget?.itens||[]).filter(x=>x.materialRequestId===r.id).reduce((a,x)=>a+Number(x.quantidade||0),0);if(r.autorizacao?.tipo==='ISENCAO'&&Number(r.autorizacao.quantidade)===held)continue;if(!technical||Math.abs(planned-held)>0.000001||r.origemMaterial!=='CLIENTE'&&(!budget||technical.statusSolicitacao!=='APROVADO_TECNICAMENTE'||Math.abs(approved-planned)>0.000001))throw Error('Devolva a peça '+r.material+' ou atualize os materiais e o orçamento aprovado com internet antes de concluir.');}}
  return {canFinish:true,local:true};
 }
 function exportCSV(){const rows=ctx.data.requests.filter(r=>master()||['entregar','faturar','tratar_ocorrencias'].some(can)||isMine(r)),columns=['OS','Cliente','Equipamento','Material','Guarda','Estado','Entregue','Recebido','Sob guarda','Aplicado','Devolvido','Prazo'];const quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv='\ufeff'+[columns,...rows.map(r=>[r.os,r.clienteNome,r.equipamentoModelo,r.material,r.guardaNome||r.tecnico,NAMES[statusKey(r)]||r.status,q(r).entregue,q(r).recebida,custody(r),q(r).utilizada,q(r).devolvida,r.prazoRetorno])].map(x=>x.map(quote).join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='CIJ-Materiais-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 async function open(os,equipment,refresh){actor();ctx.os=os;ctx.equipment=equipment;ctx.refresh=refresh;ctx.central=false;try{await load();await showViewer();}catch(e){overlay('Materiais da OS','<div class="mat-alert error">'+esc(e.message)+'</div>');}}
 window.MaterialOS={VERSION,PERMISSIONS,ctx,can,execute,load,sync,open,central,convert,release,read,custody,free,prepare:async os=>{await load(true);if(os)await workflow(os);},technicalParts,syncTechnical,validateFinish,queue:jobs,cacheData:()=>cached('data'),operate};
 window.addEventListener('portal-session-ended',()=>{epoch++;ctx.uid='';ctx.os=null;ctx.equipment=null;ctx.data={requests:[],catalog:[],staff:[],orders:[],alerts:[],history:[],quarantine:[]};document.getElementById('mat-overlay')?.remove();});
 window.addEventListener('online',()=>{if(uid()&&!window.__CIJMateriaisAssistencia)sync().then(()=>ctx.central&&load(true).then(renderCentral)).catch(()=>{});});
})();
